export const EVENTS = {
    EID_CLICKED:0,
    EID_FORCE_UPDATE:1,
    EID_ROLLBACK:2,
    EID_DELETE_SNAPSHOT:3,
    EID_NETWORK_REMOTE_STATE:4,
    EID_NETWORK_PEER_JOINED:5,
    EID_NETWORK_PEER_LEFT:6,
}